apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: slack-crawler
spec:
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          imagePullSecrets:
          - name: ghcrio
          hostIPC: true
          containers:
          - name: cypress
            image: ghcr.io/gabbersepp/slack-crawler
            volumeMounts:
              - mountPath: /e2e/data
                name: sambashare
                subPath: slack-crawler
              - mountPath: /dev/shm
                name: dshm
          volumes:
          - name: dshm
            emptyDir:
              medium: Memory
          - name: sambashare
            flexVolume:
              driver: "fstab/cifs"
              fsType: "cifs"
              secretRef:
                name: "cifs-secret"
              options:
                networkPath: "//192.168.2.126/sambashare"
                mountOptions: "uid=0"

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: slack-crawler-postprocess
spec:
  schedule: "*/30 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          imagePullSecrets:
          - name: ghcrio
          hostIPC: true
          containers:
          - name: postprocess
            image: ghcr.io/gabbersepp/slack-crawler-postprocess
            volumeMounts:
              - mountPath: /data
                name: sambashare
                subPath: slack-crawler
          volumes:
          - name: sambashare
            flexVolume:
              driver: "fstab/cifs"
              fsType: "cifs"
              secretRef:
                name: "cifs-secret"
              options:
                networkPath: "//192.168.2.126/sambashare"
                mountOptions: "uid=0"