apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-crawler-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-crawler-web
  template:
    metadata:
      labels:
        app: slack-crawler-web
    spec:
      containers:
        - name: app
          image: gabbersepp/slack-crawler-web
          volumeMounts:
          - mountPath: /usr/share/nginx/html/config
            name: sambashare
            subPath: slack-crawler/config
          ports:
          - containerPort: 80
        - name: api
          image: gabbersepp/slack-crawler-api
          ports:
          - containerPort: 8081
          volumeMounts:
          - mountPath: /data
            name: sambashare
            subPath: slack-crawler
          - mountPath: /config
            name: sambashare
            subPath: slack-crawler/config
      volumes:
      - name: sambashare
        flexVolume:
          driver: "fstab/cifs"
          fsType: "cifs"
          secretRef:
            name: "cifs-secret"
          options:
            networkPath: "//192.168.2.126/sambashare"
            mountOptions: "uid=0"
            

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: slack-crawler
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          imagePullSecrets:
          - name: ghcrio
          hostIPC: true
          containers:
          - name: cypress
            image: ghcr.io/gabbersepp/slack-crawler
            volumeMounts:
              - mountPath: /e2e/data
                name: sambashare
                subPath: slack-crawler
              - mountPath: /e2e/config
                name: sambashare
                subPath: slack-crawler/config
              - mountPath: /dev/shm
                name: dshm
            #resources:
            #  limits:
            #    cpu: "300m"
          volumes:
          - name: dshm
            emptyDir:
              medium: Memory
          - name: sambashare
            flexVolume:
              driver: "fstab/cifs"
              fsType: "cifs"
              secretRef:
                name: "cifs-secret"
              options:
                networkPath: "//192.168.2.126/sambashare"
                mountOptions: "uid=0"

---
apiVersion: v1
kind: Service
metadata:
  name: slack-crawler-client
spec:
  type: NodePort
  selector:
    app: slack-crawler-web
  ports:
  - name: web
    port: 80
    targetPort: 80
    nodePort: 30004
  - name: api
    port: 8081
    targetPort: 8081
    nodePort: 30003

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: slack-crawler-postprocess
spec:
  schedule: "15 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          imagePullSecrets:
          - name: ghcrio
          hostIPC: true
          containers:
          - name: postprocess
            image: ghcr.io/gabbersepp/slack-crawler-postprocess
            volumeMounts:
              - mountPath: /data
                name: sambashare
                subPath: slack-crawler
              - mountPath: /config
                name: sambashare
                subPath: slack-crawler/config
          volumes:
          - name: sambashare
            flexVolume:
              driver: "fstab/cifs"
              fsType: "cifs"
              secretRef:
                name: "cifs-secret"
              options:
                networkPath: "//192.168.2.126/sambashare"
                mountOptions: "uid=0"